version: '2'
services:
  db:
    image: library/mysql:5.6.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_DATABASE: rails_docker_development
      MYSQL_PASSWORD: 123456
      MYSQL_HOST: localhost
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails-docker
    ports:
      - "3000:3000"
    depends_on:
      - db
